### PR TITLE
Fix: lint replaceBy messages

### LINKED ISSUE #142: The `no-deprecated-api` replacement for `crypto.createDecipher` is incorrect
```
crypto.createDecipher was deprecated since v10.0.0. Use tls.createDecipheriv() instead.                        node/no-deprecated-api
crypto.createCipher was deprecated since v10.0.0. Use tls.createCipheriv() instead.                            node/no-deprecated-api
```

It says `tls` there, but `tls` has no such methods. It should be `crypto`.

### PR DESCRIPTION
**Pull request by LitoMore**
Fixes #142

Node.js doc: 

- [crypto.createCipher](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password_options)
- [crypto.createDecipher](https://nodejs.org/api/crypto.html#crypto_crypto_createdecipher_algorithm_password_options)

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for the fix!

Would you fix the CI failure? (probably it will be fixed with `eslint --fix`)

**Comment by LitoMore** [comment]
OK, checking...

**Comment by LitoMore** [comment]
@mysticatea Updated :)

**Comment by LitoMore** [comment]
Looks the test coverage has dropped, do I need to fill up the tests for the Node.js 10.0.0 cases?

**Comment by mysticatea** [comment]
LGTM, thank you very much!

**Pull request merged**
