### PR TITLE
Add no-callback-literal rule

### PR DESCRIPTION
**Pull request by feross**
Fixes: https://github.com/mysticatea/eslint-plugin-node/issues/178

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for your contribution!

Code looks good to me. Would you add `docs/rules/no-callback-literal.md`?

**Comment by feross** [comment]
@mysticatea I just added a documentation file as you requested.

**Comment by mysticatea** [comment]
I'm sorry that I have lost track on this. LGTM, thank you!

**Comment by feross** [comment]
Thank you @mysticatea!

**Comment by aleen42** [comment]
Holy crap rule!! I don't know why I cannot callback literal?

**Pull request merged**
