### PR TITLE
fix recommended shared config

### PR DESCRIPTION
**Pull request by kaicataldo**
I noticed this while working on https://github.com/eslint/eslint/pull/12898. This is currently causing tests to fail in that branch.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Do you want me to leave this open?

**Comment by mysticatea** [comment]
Yes, please. I will make the next major release after the new espree that includes ES2020 syntaxes is released.

**Comment by thernstig** [comment]
@mysticatea the new ES2020 have been released, right? Any plans to release a new version with the fixes? :)

**Comment by thernstig** [comment]
@kaicataldo you just got tired of waiting? :(

**Pull request closed without merging**
