### PR TITLE
fix dynamic import

### PR DESCRIPTION
**Pull request by fisker**
fixes: #200

### CODE REVIEW

**Comment by ehmicky** [comment]
Would it be possible to make a release @mysticatea?
Thanks @fisker and @mysticatea for this PR.

**Comment by mysticatea** [comment]
I have published: https://github.com/mysticatea/eslint-plugin-node/releases/tag/v11.0.0

**Comment by ehmicky** [comment]
Thanks a lot @mysticatea!

**Comment by pagarwal-ignitetech** [comment]
This bug still exist in latest v11.1.0 of eslint-plugin-node for no-duplicate-case and few others
```logs
" --> stderr: TypeError: Cannot read property 'indexOf' of undefined"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: Occurred while linting /tmp/github.com/trilogy-group/alpha-coach-bot/data/amplify/backend/function/importCommonLitData/src/index.ts:2"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at stripImportPathParams (/node_modules/eslint-plugin-node/lib/util/strip-import-path-params.js:8:20)"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at ExportAllDeclaration,ExportNamedDeclaration,ImportDeclaration,ImportExpression (/node_modules/eslint-plugin-node/lib/util/visit-import.js:55:40)"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at /node_modules/eslint/lib/linter/safe-emitter.js:45:58"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at Array.forEach (<anonymous>)"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at Object.emit (/node_modules/eslint/lib/linter/safe-emitter.js:45:38)"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at NodeEventGenerator.applySelector (/node_modules/eslint/lib/linter/node-event-generator.js:256:26)"
Error
2021-08-16 08:59:05.500 IST
finder-job-df4b88
" --> stderr: at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/linter/node-event-generator.js:285:22)"
```

**Pull request merged**
