### PR TITLE
plugin section for the eslintrc file in the README

### PR DESCRIPTION
**Pull request by cirpo**
- better markdown table formatting

### CODE REVIEW

**Comment by cirpo** [comment]
I was getting 
```
  1:1  error  Definition for rule 'node/no-deprecated-api' was not found        node/no-deprecated-api
  1:1  error  Definition for rule 'node/no-extraneous-require' was not found    node/no-extraneous-require
  1:1  error  Definition for rule 'node/no-missing-require' was not found       node/no-missing-require
  1:1  error  Definition for rule 'node/no-unpublished-bin' was not found       node/no-unpublished-bin
  1:1  error  Definition for rule 'node/no-unpublished-require' was not found   node/no-unpublished-require
  1:1  error  Definition for rule 'node/no-unsupported-features' was not found  node/no-unsupported-features
  1:1  error  Definition for rule 'node/process-exit-as-throw' was not found    node/process-exit-as-throw
  1:1  error  Definition for rule 'node/shebang' was not found                  node/shebang
```

@mysticatea I spent quite some time to figure out that the error was just because I forgot to import the plugin in the eslintrc, maybe this PR will save some other people's time :P

**Comment by mysticatea** [comment]
Thank you for this PR.

However, 

- that table is auto-generated by the script [scripts/update.js](https://github.com/mysticatea/eslint-plugin-node/blob/e957849ce0691794741fb793cab0e61090773340/scripts/update.js). You have to modify the script if you want to format the table.
- see #116 about the example in README.md.

**Comment by cirpo** [comment]
@mysticatea in the meantime I'm going to open a PR adding only the "plugin" part. thanks

**Comment by mysticatea** [comment]
Please check #116, about `"plugin"` part.

> 9425f68 added plugins: ["node"] to the recommended config, but I have not published it. I will publish it at the next major release I'm writing to support Node 10 things.
> https://github.com/mysticatea/eslint-plugin-node/pull/116#issuecomment-389083748

**Comment by cirpo** [comment]
👍

**Pull request closed without merging**
